LibraryApp.WEB/Controllers/BrochureController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using LibraryApp.BLL.ViewModels;
using System.Web.Mvc;
using LibraryApp.BLL.Services;
using System.Collections.Generic;

namespace LibraryApp.WEB.Controllers
{
    public class BrochureController : Controller
    {
        private BrochureService brochureService;

        public BrochureController(BrochureService serv)
        {
            brochureService = serv;
        }

        public ActionResult Index()
        {
            if (User.IsInRole("admin"))
            {
                return View("Index", "~/Views/Shared/_AdminLayout.cshtml");
            }
            return View("ViewForUsers");
        }

        public ActionResult Read()
        {
            IEnumerable<BrochureViewModel> brochures = brochureService.GetAllObjects();
            return Json(brochures);
        }

        [HttpPost]
        public ActionResult Update(BrochureViewModel brochure)
        {
            if (ModelState.IsValid)
            {
                brochureService.UpdateObject(brochure);
            }

            return Json(new[] { brochure }.ToDataSourceResult(new DataSourceRequest(), ModelState));
        }

        [HttpPost]
        public ActionResult Create(BrochureViewModel brochure)
        {
            if (ModelState.IsValid)
            {
                brochure.BrochureId = brochureService.CreateObject(brochure);
            }

            return Json(new[] { brochure }.ToDataSourceResult(new DataSourceRequest(), ModelState), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Destroy(BrochureViewModel brochure)
        {
            if (ModelState.IsValid)
            {
                brochureService.DeleteObject(brochure);
            }
            return Json(new[] { brochure }.ToDataSourceResult(new DataSourceRequest(), ModelState));
        }
        public JsonResult GetAllAuthors()
        {
            IEnumerable<AuthorViewModel> authors = brochureService.GetAuthors();
            return Json(authors, JsonRequestBehavior.AllowGet);
        }
    }
}

LibraryApp.WEB/Controllers/GridController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System.Web.Mvc;
using LibraryApp.BLL.ViewModels;
using LibraryApp.BLL.Services;
using System.Collections.Generic;

namespace LibraryApp.WEB.Controllers
{
    public class GridController : Controller
    {
        private BookService bookService;

        public GridController(BookService serv)
        {
            bookService = serv;
        }

        public ActionResult Index()
        {
            if (User.IsInRole("admin"))
            {
                return View("Index", "~/Views/Shared/_AdminLayout.cshtml");
            }
            return View("ViewForUsers");
        }

        public ActionResult Read()
        {
            IEnumerable<BookViewModel> books = bookService.GetAllObjects();
            return Json(books);
        }

        [HttpPost]
        public ActionResult Update(BookViewModel book)
        {

            if (ModelState.IsValid)
            {
                bookService.UpdateObject(book);
            }

            return Json(new[] { book }.ToDataSourceResult(new DataSourceRequest(), ModelState));
        }

        [HttpPost]
        public ActionResult Create(BookViewModel book)
        {

            if (ModelState.IsValid)
            {
                book.BookId = bookService.CreateObject(book);

            }

            return Json(new[] { book }.ToDataSourceResult(new DataSourceRequest(), ModelState), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Destroy(BookViewModel book)
        {
            if (ModelState.IsValid)
            {
                bookService.DeleteObject(book);
            }
            return Json(new[] { book }.ToDataSourceResult(new DataSourceRequest(), ModelState));
        }
        public JsonResult GetAllAuthors()
        {
            IEnumerable<AuthorViewModel> authors = bookService.GetAuthors();
            return Json(authors, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetAllGenres()
        {
            IEnumerable<GenreViewModel> genres = bookService.GetAllGenres();
            return Json(genres, JsonRequestBehavior.AllowGet);
        }
    }
}

LibraryApp.WEB/Controllers/PublicationController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using LibraryApp.BLL.ViewModels;
using System.Web.Mvc;
using LibraryApp.BLL.Services;
using System.Collections.Generic;

namespace LibraryApp.WEB.Controllers
{
    public class PublicationController : Controller
    {
        private PublicationService publicationService;

        public PublicationController(PublicationService serv)
        {
            publicationService = serv;
        }

        public ActionResult Index()
        {
            if (User.IsInRole("admin"))
            {
                return View("Index", "~/Views/Shared/_AdminLayout.cshtml");
            }
            return View("ViewForUsers");
        }

        public ActionResult Read()
        {
            IEnumerable<PublicationViewModel> publications = publicationService.GetAllObjects();
            return Json(publications);
        }

        [HttpPost]
        public ActionResult Update(PublicationViewModel publication)
        {
            if (ModelState.IsValid)
            {
                publicationService.UpdateObject(publication);
            }
            return Json(new[] { publication }.ToDataSourceResult(new DataSourceRequest(), ModelState));
        }

        [HttpPost]
        public ActionResult Create(PublicationViewModel publication)
        {

            if (ModelState.IsValid)
            {
                publication.PublicationId = publicationService.CreateObject(publication);
            }

            return Json(new[] { publication }.ToDataSourceResult(new DataSourceRequest(), ModelState), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Destroy(PublicationViewModel publication)
        {
            if (ModelState.IsValid)
            {
                publicationService.DeleteObject(publication);
            }
            return Json(new[] { publication }.ToDataSourceResult(new DataSourceRequest(), ModelState));
        }
        public JsonResult GetAllAuthors()
        {
            IEnumerable<AuthorViewModel> authors = publicationService.GetAuthors();
            return Json(authors, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetAllGenres()
        {
            IEnumerable<SubscriptionViewModel> genres = publicationService.GetAllSubscriptions();
            return Json(genres, JsonRequestBehavior.AllowGet);
        }
    }
}

LibraryApp.WEB/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    @Scripts.Render("~/bundles/jquery")
    <link href="https://kendo.cdn.telerik.com/2018.1.117/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.1.117/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.1.117/styles/kendo.default.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2018.1.117/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.117/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.117/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.117/js/kendo.aspnetmvc.min.js"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-inverse bg-dark fixed-top">
            <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsexampledefault" aria-controls="navbarsexampledefault" aria-expanded="false" aria-label="toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Library</a>
            <div class="collapse navbar-collapse" id="navbarsexampledefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            Home <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">settings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">help</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">search</button>
                </form>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-sm-3  sidebar">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("Index", "Home")">
                            Overview <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Grid")">Edit Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Publication")">Edit Publications</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Brochure")">Edit Brochures</a>
                    </li>
                </ul>
            </nav>
            <main class="col-sm-9 ">
                @RenderBody()
            </main>
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LibraryApp.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

	<!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
	@Scripts.Render("~/bundles/jquery")
	<link href="https://kendo.cdn.telerik.com/2018.1.117/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
	<link href="https://kendo.cdn.telerik.com/2018.1.117/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
	<link href="https://kendo.cdn.telerik.com/2018.1.117/styles/kendo.default.min.css" rel="stylesheet" type="text/css" />
	<script src="https://kendo.cdn.telerik.com/2018.1.117/js/jquery.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2018.1.117/js/jszip.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2018.1.117/js/kendo.all.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2018.1.117/js/kendo.aspnetmvc.min.js"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <div class="container">
        <header class="masthead">
            <h3 class="text-muted">Library</h3>
            <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav text-md-center nav-justified w-100">
                        <li class="nav-item active">
                            <a class="nav-link" href="@Url.Action("Index", "Home")">
                                Library
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Grid")">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Publication")">Publications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Brochure")">Brochures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Contact", "Home")">Contacts</a>
                        </li>
                        
                            @Html.Partial("_LoginPartial")                        
                    </ul>
                    
                </div>
            </nav>
        </header>
        <div class="jumbotron">
            <h1>Library</h1>
            <p class="lead">Read books more!</p>
            <p>
                <a class="btn btn-lg btn-success" href="#" role="button">Get started today</a>
            </p>
        </div>
        @RenderBody()
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-lg-4">
                <h2>Books</h2>
                <p>Love reading books? Get more below! </p>
                <p>
                    <a class="btn btn-primary" href="@Url.Action("Index", "Grid")" role="button">More books &raquo;</a>
                </p>
            </div>
            <div class="col-lg-4">
                <h2>Publications</h2>
                <p>Love reading publications? Get more below! </p>
                <p>
                    <a class="btn btn-danger" href="@Url.Action("Index", "Publication")" role="button">More publications &raquo;</a>
                </p>
            </div>
            <div class="col-lg-4">
                <h2>Brochures</h2>
                <p>Love reading brochures? Get more below!</p>
                <p>
                    <a class="btn btn-info" href="@Url.Action("Index", "Brochure")" role="button">More Brochures &raquo;</a>
                </p>
            </div>
        </div>
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>